# Site settings
title: Infiniteloops
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://infiniteloops.co" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
collections:
  docs:
    output: true
    layout: doc
    permlink: /docs/:version/:path/
# Build settings
markdown: kramdown
slim:
  pretty: true
  format: html5
sass:
  style: compressed
